<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>legged_ros2_control</name>
  <version>0.0.0</version>
  <description>Legged ROS2 control</description>
  <maintainer email="zitongbai@outlook.com">xiaobaige</maintainer>
  <maintainer email="v.hahm@vinmotion.net">Ha Hoang</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake_ros</buildtool_depend>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>rclpy</depend>

  <depend>controller_manager</depend>
  <depend>controller_manager_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>rclcpp</depend>
  <depend>realtime_tools</depend>
  <depend>rosgraph_msgs</depend>
  <depend>std_msgs</depend>
  <depend>urdf</depend>


  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
